

# RUTA DEL INICIO DE LA TABLA TODO
todo_index:
   path: /
   controller: App\Controller\TodoController::index

   
#RUTA FORMULARIO AÃ‘ADIR EN LISTA
todo_formulario:
   path: /todo/formulario
   controller: App\Controller\TodoController::formulario_add

   
   
# RUTA PARA GUARDAR TAREA   
todo_save:
    path: /todo/save
    controller: App\Controller\TodoController::save
   
# RUTA PARA LISTAR TODO
todo_listar:
    path: /todo/listar
    controller: App\Controller\TodoController::visualizarlistado


# RUTA PARA MODIFICAR EL ESTADO DE UNA TAREA A REALIZADA
todo_modificar_estado:
    path: /todo/modificar_estado/{id}
    controller: App\Controller\TodoController::marcar_tarea_realizada
    
# RUTA LOGIN
login:
    path: /login
    controller: App\Controller\UserController::login
    
#RUTA LOGOUT
logout:
    path: /logout
    
# RUTA REGISTRO USUARIOS 
register:
    path: /registro
    controller: App\Controller\UserController::register
    
    